name: hello

on: [push]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: step 1
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Step two
      run: env | sort
  job2:
    name: 2 job
    runs-on: windows-latest
    steps:
    - name: step 1
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: "Get-ChildItem Env: | Sort-Object Name"
      